from pushforward_operators.fast_non_linear_vector_quantile_regression.vqr.cvqf import DiscreteCVQF
from pushforward_operators.fast_non_linear_vector_quantile_regression.vqr.solvers.cvx import CVXVQRSolver
from pushforward_operators.fast_non_linear_vector_quantile_regression.vqr.solvers.pot import POTVQESolver
from pushforward_operators.fast_non_linear_vector_quantile_regression.vqr.solvers.base import Solver, VQESolver, VQRSolver, DiscreteSolver
from pushforward_operators.fast_non_linear_vector_quantile_regression.vqr.solvers.regularized_lse import (
    RegularizedDualVQRSolver,
    MLPRegularizedDualVQRSolver,
)
